import { DecisionAnalysis } from "../types";

const STORAGE_KEY = "the_tiebreaker_saved_decisions";

export function loadSavedDecisions(): DecisionAnalysis[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    return JSON.parse(raw);
  } catch (e) {
    console.error("Failed to load decisions from localStorage", e);
    return [];
  }
}

export function saveDecision(analysis: DecisionAnalysis): void {
  try {
    const existing = loadSavedDecisions();
    const index = existing.findIndex((d) => d.id === analysis.id);
    if (index >= 0) {
      existing[index] = analysis;
    } else {
      existing.unshift(analysis);
    }
    localStorage.setItem(STORAGE_KEY, JSON.stringify(existing.slice(0, 50)));
  } catch (e) {
    console.error("Failed to save decision", e);
  }
}

export function deleteSavedDecision(id: string): DecisionAnalysis[] {
  try {
    const existing = loadSavedDecisions();
    const filtered = existing.filter((d) => d.id !== id);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(filtered));
    return filtered;
  } catch (e) {
    console.error("Failed to delete decision", e);
    return [];
  }
}

export function exportDecisionAsMarkdown(analysis: DecisionAnalysis): string {
  const recommended = analysis.options.find(
    (o) => o.id === analysis.verdict.recommendedOptionId
  ) || analysis.options[0];

  let md = `# Decision Analysis: ${analysis.title}\n`;
  md += `**Date:** ${new Date(analysis.createdAt).toLocaleDateString()} | **Category:** ${analysis.category}\n\n`;
  
  if (analysis.context) {
    md += `## Context & Constraints\n${analysis.context}\n\n`;
  }

  md += `## 🏆 The Tiebreaker Verdict\n`;
  md += `**Recommended Choice:** **${recommended?.name}** (Confidence: ${analysis.verdict.confidenceScore}%)\n`;
  md += `**Decision Type:** ${analysis.verdict.reversibilityType === 'one-way-door' ? '🚪 One-Way Door (Irreversible / High Stakes)' : '🔄 Two-Way Door (Reversible)'}\n\n`;
  md += `### Executive Summary\n${analysis.verdict.executiveSummary}\n\n`;
  
  md += `### Why This Option Wins\n`;
  analysis.verdict.whyThisWins.forEach((w) => {
    md += `- ${w}\n`;
  });
  md += `\n`;

  if (analysis.verdict.keyTradeoffs.length) {
    md += `### Key Trade-Offs to Accept\n`;
    analysis.verdict.keyTradeoffs.forEach((t) => {
      md += `- ${t}\n`;
    });
    md += `\n`;
  }

  md += `## ⚖️ Pros & Cons Breakdown\n\n`;
  analysis.options.forEach((opt) => {
    md += `### ${opt.name}\n`;
    md += `**Pros:**\n`;
    opt.pros.forEach((p) => {
      md += `+ [${p.impact.toUpperCase()}] ${p.text} (+${p.score})\n`;
    });
    md += `\n**Cons:**\n`;
    opt.cons.forEach((c) => {
      md += `- [${c.impact.toUpperCase()}] ${c.text} (${c.score})\n`;
    });
    md += `\n`;
  });

  md += `## 🧩 SWOT Analysis\n\n`;
  analysis.options.forEach((opt) => {
    md += `### ${opt.name}\n`;
    md += `- **Strengths:** ${opt.swot.strengths.join(", ") || "None listed"}\n`;
    md += `- **Weaknesses:** ${opt.swot.weaknesses.join(", ") || "None listed"}\n`;
    md += `- **Opportunities:** ${opt.swot.opportunities.join(", ") || "None listed"}\n`;
    md += `- **Threats:** ${opt.swot.threats.join(", ") || "None listed"}\n\n`;
  });

  md += `## ⏳ The 10/10/10 Perspective\n\n`;
  analysis.options.forEach((opt) => {
    const t = analysis.tenTenTenRule[opt.id];
    if (t) {
      md += `### ${opt.name}\n`;
      md += `- **In 10 Minutes:** ${t.in10Minutes}\n`;
      md += `- **In 10 Months:** ${t.in10Months}\n`;
      md += `- **In 10 Years:** ${t.in10Years}\n\n`;
    }
  });

  if (analysis.regretMinimizationAnalysis) {
    md += `## 👴 Regret Minimization Framework\n${analysis.regretMinimizationAnalysis}\n\n`;
  }

  if (analysis.blindSpots.length) {
    md += `## 🔍 Blind Spot & Bias Detection\n\n`;
    analysis.blindSpots.forEach((b) => {
      md += `### ${b.title}\n`;
      md += `- **Risk:** ${b.description}\n`;
      md += `- **Mitigation:** ${b.mitigation}\n\n`;
    });
  }

  if (analysis.actionSteps.length) {
    md += `## 🚀 Immediate Next Steps\n\n`;
    analysis.actionSteps.forEach((s, idx) => {
      md += `${idx + 1}. [ ] ${s}\n`;
    });
    md += `\n`;
  }

  md += `---\n*Generated by The Tiebreaker AI Decision Intelligence*`;
  return md;
}
